#cloud-config
autoinstall:
  version: 1
  identity:
    realname: 'Raul Coelho'
    hostname: ubuntu-desktop
    username: rpc
    password: '$y$j9T$AKKR4MdzvNLW6PLy84a7/.$gHQhcrFbP.6klveBfzLk3xeoONhnK.hIjWsIx50mRCD'
  locale: en_US.utf8
  keyboard:
    layout: br
  timezone: 'America/Sao_Paulo'
  packages:
    - git
    - wget
    - curl
    - obs-studio
    - neofetch
    - tilix
    - vlc
    - htop
    - gparted
    - gnome-tweaks
    - flameshot
    - virtualbox
    - gdu
    - neovim
    - flatpak
  snaps:
    - name: spotify
      channel: stable
      classic: false
    - name: postman
      channel: stable
      classic: false
    - name: remmina
      channel: latest/stable
      classic: false
  codecs:
    install: true
  drivers:
    install: true
  updates: all
  shutdown: reboot
